### ISSUE TITLE
Racial whitelist broken again

### ISSUE THREAD

**Issue by Cameron653** [SpadesNeil/VOREstation#627]
Exactly what it says in the title.
For whatever reason, it'd appear that skeletons, Vox, and Diona aren't actually whitelisted. Possibly caused by the whitelist update.

**Comment by SpadesNeil** [comment]
Pretty sure this was resolved.

**Comment by Cameron653** [comment]
Just tested it on the server. This bug still exists.

http://puu.sh/oIHRm/b191d9f708.png

**Comment by SpadesNeil** [comment]
Were you admin on the test server?

**Comment by Cameron653** [comment]
This was on the main server, not the test server. As in, the actual server.

**Comment by SpadesNeil** [comment]
Try other species.

**Comment by Cameron653** [comment]
Going to test the other species. Will edit with results.

**Comment by SpadesNeil** [comment]
Going to close this as it's technically a duplicate of an earlier issue which is being reopened.

**Comment by SpadesNeil** [comment]
Okay, no, that was a PR. Not an issue. Wtf. Stupid Github search function.

**Comment by Cameron653** [comment]
Er, that's a PR. Not an issue.

**Comment by SpadesNeil** [comment]
#29 is what I meant but it's not quite a duplicate.
